POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Bekzod",
  "surname": "Qoraxonov",
  "email": "t.lochin.98@gmail.com",
  "password": "7777",
  "phone": "998998621524"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "t.lochin.98@gmail.com",
  "password": "7777"
}

###
POST http://localhost:8080/auth/verification
Content-Type: application/json

{
  "phone": "998998621534",
  "code": "91319"
}
###
GET http://localhost:8080/auth/resend/email/t.lochin.98@gmail.com